name: Auto Label Hacktoberfest PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Hacktoberfest Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "hacktoberfest-accepted"
